import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdtempSync,readFileSync,writeFileSync,mkdirSync,statSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const require=createRequire(import.meta.url);
const {config,install}=require('../app/src/main/assets/setup/configure.cjs');
const home=mkdtempSync(join(tmpdir(),'maestro-test-'));
mkdirSync(join(home,'.openclaw'));writeFileSync(join(home,'.openclaw','openclaw.json'),'existing default profile');
mkdirSync(join(home,'.termux'));writeFileSync(join(home,'.termux','termux.properties'),'font-size=14\nallow-external-apps=false\n');
const bundle={key:'fixture-only-no-real-key',bridge:'fixture-bridge',gateway:'fixture-gateway',plugin:{'index.js':'// plugin','package.json':'{}','openclaw.plugin.json':'{}'}};
install(bundle,home);
const p=join(home,'.openclaw-maestro','openclaw.json'), c=JSON.parse(readFileSync(p));
assert.equal(c.models.providers.openai.agentRuntime.id,'openclaw');
assert.equal(c.models.providers.openai.api,'openai-responses');
assert.equal(c.agents.defaults.model.primary,'openai/gpt-6-astra');
assert.equal(c.agents.defaults.thinkingDefault,'high');
assert.deepEqual(c.agents.defaults.model.fallbacks,[]);
assert.equal(c.gateway.bind,'loopback');assert.equal(c.gateway.auth.token,bundle.gateway);
assert.equal(c.models.providers.openai.models[0].reasoning,true);
assert.equal(c.tools.elevated.enabled,false);assert(!c.tools.allow.includes('exec'));
assert.equal(statSync(p).mode & 0o777,0o600);
assert.equal(readFileSync(join(home,'.openclaw','openclaw.json'),'utf8'),'existing default profile');
assert(!readFileSync(join(home,'.maestro','start.sh'),'utf8').includes(bundle.key));
install({...bundle,gateway:'new-fixture-token'},home);
assert(readdirSync(join(home,'.openclaw-maestro')).some(n=>n.startsWith('openclaw.json.backup-')));
const properties=readFileSync(join(home,'.termux','termux.properties'),'utf8');
assert(properties.includes('font-size=14'));assert.equal(properties.match(/allow-external-apps=true/g).length,1);
console.log('PASS: isolated profile, Responses/high reasoning, no fallback, permissions, backup and repeat setup');
