package br.com.maestro;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.os.*;import android.speech.RecognizerIntent;import android.speech.tts.TextToSpeech;import android.text.InputType;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;
import org.json.*;import java.io.*;import java.text.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;

public final class MainActivity extends Activity {
 private static final int BG=0xff101d2a,CARD=0xff1a2a3a,INK=0xfff5f0e8,MUTED=0xff9eafbe,GOLD=0xffe3b678,GREEN=0xff8ac5a6;
 private LinearLayout root,body;private EditText input;private TextView status;private Button submit;private ScrollView scroll;
 private final Pairing pairing=new Pairing();private volatile boolean gatewayTesting=false;private String setupPhase="";
 private SharedPreferences prefs;private Vault vault;private JSONObject plan;private JSONArray history=new JSONArray();private String page="mission",mode="cloud",phase="Pronto para sua próxima ideia",lastRequest="";private String session;
 private volatile boolean busy=false,destroyed=false;private final ExecutorService worker=Executors.newSingleThreadExecutor();private final AtomicBoolean inferencing=new AtomicBoolean(false);private final AtomicInteger generation=new AtomicInteger();private Net.Job job;private Bridge bridge;private TextToSpeech tts;private boolean ttsReady=false,bridgeReady=false;private int selected=-1;private final List<JSONObject> pending=new ArrayList<>();
 @Override public void onCreate(Bundle state){super.onCreate(state);try{
  prefs=getSharedPreferences("maestro",0);vault=new Vault(this);mode=prefs.getString("mode","cloud");session=prefs.getString("session",UUID.randomUUID().toString());prefs.edit().putString("session",session).apply();
  lastRequest=prefs.getString("request","");String stored=prefs.getString("plan","");if(!stored.isEmpty())try{plan=new JSONObject(stored);selected=prefs.getInt("selected",-1);}catch(Exception ignored){}try{history=new JSONArray(prefs.getString("history","[]"));}catch(Exception ignored){}
  if(vault.get("bridge").isEmpty())vault.put("bridge",UUID.randomUUID().toString()+UUID.randomUUID());
  tts=new TextToSpeech(this,s->{ttsReady=s==TextToSpeech.SUCCESS;if(ttsReady)tts.setLanguage(new Locale("pt","BR"));});
  try{bridge=new Bridge(vault.get("bridge"),pairing,this::bridgeRequest);bridgeReady=true;}catch(Exception e){log("Ponte local indisponível: "+e.getMessage());}
  if(prefs.getInt("setupVersion",0)<2){prefs.edit().putString("cloudModel",Reasoning.MODEL).putInt("setupVersion",2).putBoolean("cloudVerified",false).apply();page="engines";}
  setupPhase=prefs.getString("setupPhase","");render();
 }catch(Throwable e){TextView failure=new TextView(this);failure.setPadding(32,80,32,32);failure.setText("Maestro não conseguiu iniciar.\n"+e.getClass().getSimpleName()+": "+e.getMessage());failure.setTextSize(20);setContentView(failure);}}
 private int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);}
 private GradientDrawable bg(int c,float radius){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(radius));return d;}
 private LinearLayout vertical(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
 private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(0);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 private TextView text(String s,int sp,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);t.setLineSpacing(dp(3),1);return t;}
 private void add(LinearLayout p,View v,int top){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(top);p.addView(v,lp);}
 private Button button(String label,boolean primary,Runnable r){Button b=new Button(this);b.setText(label);b.setTextSize(15);b.setAllCaps(false);b.setTextColor(primary?BG:INK);b.setTypeface(Typeface.create("sans-serif-medium",0));b.setBackground(bg(primary?GOLD:0xff283c4e,14));b.setMinHeight(dp(48));b.setPadding(dp(14),dp(8),dp(14),dp(8));b.setOnClickListener(v->r.run());return b;}
 private LinearLayout card(){LinearLayout c=vertical();c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(bg(CARD,22));add(body,c,14);return c;}
 private void label(LinearLayout p,String s){TextView t=text(s,11,GOLD);t.setLetterSpacing(.12f);add(p,t,0);}
 private void title(LinearLayout p,String s,int size){TextView t=text(s,size,INK);t.setTypeface(Typeface.create("sans-serif-medium",0));add(p,t,8);}
 private void paragraph(LinearLayout p,String s){TextView t=text(s,15,MUTED);t.setTextIsSelectable(true);add(p,t,8);}
 private void render(){if(destroyed)return;root=vertical();root.setBackgroundColor(BG);root.setPadding(dp(20),dp(10),dp(20),dp(8));root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(dp(20),dp(10)+insets.getSystemWindowInsetTop(),dp(20),dp(8)+insets.getSystemWindowInsetBottom());return insets;});setContentView(root);root.requestApplyInsets();
  LinearLayout header=row();TextView brand=text("M A E S T R O",18,GOLD);brand.setTypeface(Typeface.create("sans-serif-medium",0));header.addView(brand,new LinearLayout.LayoutParams(0,dp(45),1));Button sound=button("◉",false,()->speak(plan==null?"Olá, Edward. Qual é a missão?":plan.optString("summary")));header.addView(sound,new LinearLayout.LayoutParams(dp(48),dp(42)));add(root,header,0);
  LinearLayout tabs=row();for(String[]p:new String[][]{{"mission","Missão"},{"engines","Motores"},{"journal","Registro"}}){Button b=button(p[1],page.equals(p[0]),()->{page=p[0];render();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(43),1);lp.setMargins(dp(3),0,dp(3),0);tabs.addView(b,lp);}add(root,tabs,10);
  scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);body=vertical();body.setPadding(0,dp(14),0,dp(20));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  if(page.equals("engines"))engines();else if(page.equals("journal"))journal();else mission();
  if(page.equals("mission"))composer();
 }
 private void mission(){
  label(body,"SEU ASSISTENTE, EM AÇÃO");title(body,plan==null?"Sua ideia.\nEm movimento.":"Vamos fazer\nacontecer.",34);
  paragraph(body,plan==null?"Fale o que você quer. Maestro organiza o plano e prepara os próximos passos.":lastRequest);
  status=text((busy?"●  ":"○  ")+phase,13,busy?GOLD:GREEN);add(body,status,14);
  LinearLayout strip=card();label(strip,mode.equals("local")?"QWEN · NO APARELHO":mode.equals("claw")?"OPENCLAW · NO CELULAR":"OPENAI + AÇÕES LOCAIS");paragraph(strip,mode.equals("local")?"Ideias offline. Não consulta lugares, preços ou horários atuais.":mode.equals("claw")?"GPT-6 Astra raciocina; OpenClaw executa neste celular.":"Planejamento na nuvem. Você acompanha cada ação no Android.");
  if(plan==null){LinearLayout examples=card();label(examples,"COMECE COM UMA MISSÃO");add(examples,button("Planejar uma noite com amigos  ↗",true,()->setPrompt("Somos 4 amigos. Planeje uma noite hoje em "+prefs.getString("city","São Paulo")+" até R$100 por pessoa. Busque 3 opções e prepare o convite.")),14);add(examples,button("Um encontro com crianças",false,()->setPrompt("Somos 6 pessoas, incluindo uma criança de 5 anos. Quero um passeio em "+prefs.getString("city","São Paulo")+" com orçamento de R$60 por pessoa. Compare 3 opções.")),10);add(examples,button("Criar uma brincadeira offline",false,()->{mode="local";prefs.edit().putString("mode",mode).apply();setPrompt("Crie uma investigação divertida de 10 minutos para amigos usando uma chave, um livro e um copo. Inclua três pistas e a solução.");}),10);}
  if(plan==null)add(body,button("Testar ações sem configurar IA",false,this::preview),14);
  else renderPlan();
 }
 private void preview(){try{plan=new JSONObject().put("title","Uma noite em casa").put("summary","Demonstração pré-definida, sem IA: cada amigo traz um prato, vocês escolhem uma música e jogam uma rodada de perguntas. Use os botões abaixo para testar as ações reais do Android.").put("invite","Pessoal, vamos combinar uma noite em casa? Cada um leva um prato e uma música para compartilhar. Vamos escolher juntos o horário!").put("options",new JSONArray()).put("sources",new JSONArray()).put("searched",false).put("engine","DEMONSTRAÇÃO · SEM GERAÇÃO POR IA");lastRequest="Teste de salvar, ouvir e compartilhar";selected=-1;savePlan();phase="Exemplo carregado. As ações abaixo são reais.";log("Exemplo pré-definido aberto · não é resposta de IA");render();}catch(Exception e){toast(safeMessage(e));}}
 private void composer(){LinearLayout box=vertical();box.setPadding(0,dp(8),0,0);input=new EditText(this);input.setTextColor(INK);input.setHintTextColor(MUTED);input.setTextSize(16);input.setHint(plan==null?"Qual é a missão?":"Mudou o plano? Conte o que mudou…");input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);input.setMaxLines(3);input.setPadding(dp(14),dp(10),dp(14),dp(10));input.setBackground(bg(CARD,14));add(box,input,0);
  LinearLayout actions=row();Button mic=button("Falar",false,this::voice);actions.addView(mic,new LinearLayout.LayoutParams(dp(83),dp(48)));submit=button(busy?"Parar":"Planejar  →",true,()->{if(busy)cancel();else start(input.getText().toString());});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(48),1);lp.leftMargin=dp(10);actions.addView(submit,lp);add(box,actions,8);add(root,box,0);
 }
 private void setPrompt(String s){if(!page.equals("mission")){page="mission";render();}if(input!=null){input.setText(s);input.setSelection(s.length());}}
 private void renderPlan(){
  LinearLayout intro=card();label(intro,plan.optString("engine","PLANO"));title(intro,plan.optString("title"),24);paragraph(intro,plan.optString("summary"));String meta=plan.optBoolean("searched")?"Pesquisa web realizada · confira disponibilidade":"Sem verificação de disponibilidade em tempo real";paragraph(intro,meta);if(plan.has("seconds"))paragraph(intro,"Preparado em "+plan.optString("seconds")+" s");
  JSONArray options=plan.optJSONArray("options");if(options!=null)for(int i=0;i<options.length();i++){final int at=i;JSONObject o=options.optJSONObject(i);if(o==null)continue;LinearLayout c=card();label(c,(selected==i?"ESCOLHIDA":"OPÇÃO "+(i+1))+"  /  "+o.optString("cost","Confirmar preço"));title(c,o.optString("name"),22);paragraph(c,o.optString("why"));add(c,button(selected==i?"Selecionada  ✓":"Escolher esta opção",selected==i,()->{selected=at;savePlan();log("Opção escolhida: "+o.optString("name"));render();}),12);add(c,button("Ver no mapa  ↗",false,()->openMap(o.optString("query"))),8);}
  LinearLayout execute=card();label(execute,"PRÓXIMOS PASSOS");add(execute,button("Preparar convite",true,this::reviewInvite),12);add(execute,button("Salvar plano no celular",false,this::saveNoteFromPlan),8);add(execute,button("Ouvir resumo",false,()->speak(plan.optString("summary"))),8);
  JSONArray sources=plan.optJSONArray("sources");if(sources!=null&&sources.length()>0){LinearLayout c=card();label(c,"FONTES CONSULTADAS");for(int i=0;i<Math.min(sources.length(),8);i++){JSONObject source=sources.optJSONObject(i);if(source==null)continue;String url=source.optString("url");add(c,button(source.optString("title","Abrir fonte"),false,()->openWeb(url)),8);}}
  add(body,button("Nova missão",false,()->{plan=null;selected=-1;lastRequest="";session=UUID.randomUUID().toString();prefs.edit().remove("plan").remove("request").putString("session",session).apply();render();}),20);
 }
 private void start(String request){String q=request.trim();if(q.isEmpty()||busy)return;if(q.length()>5000){toast("Use até 5.000 caracteres.");return;}if(command(q))return;
  if(mode.equals("local")&&!modelReady()){page="engines";render();toast("Baixe o modelo para usar o modo local.");return;}
  if(mode.equals("cloud")&&vault.get("openai").isEmpty()){page="engines";render();toast("Configure a OpenAI para pesquisar e planejar.");return;}
  if(mode.equals("cloud")&&!prefs.getBoolean("cloudConsent",false)){new AlertDialog.Builder(this).setTitle("Planejamento com OpenAI").setMessage("Seu pedido, a cidade informada e o plano anterior serão enviados à OpenAI. A pesquisa usa a internet. Nenhuma tela ou conversa de outros aplicativos será capturada.").setNegativeButton("Agora não",null).setPositiveButton("Continuar",(d,w)->{prefs.edit().putBoolean("cloudConsent",true).apply();start(q);}).show();return;}
  if(mode.equals("claw")&&vault.get("gateway").isEmpty()){page="engines";render();toast("Configure e teste o Gateway local.");return;}
  ((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(input.getWindowToken(),0);
  String context="Data local: "+new SimpleDateFormat("yyyy-MM-dd HH:mm z",Locale.ROOT).format(new Date())+"\nCidade informada: "+prefs.getString("city","São Paulo")+"\n";
  if(plan!=null)context+="Pedido anterior: "+lastRequest+"\nPlano anterior: "+plan.toString()+"\n";
  final String prompt=context+"Novo pedido: "+q;final String engine=mode;final int task=generation.incrementAndGet();busy=true;phase=engine.equals("local")?"Criando no aparelho…":engine.equals("claw")?"Consultando seu OpenClaw…":"Pesquisando e organizando opções…";job=new Net.Job();final Net.Job work=job;final long started=System.nanoTime();lastRequest=q;render();getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
  worker.execute(()->{try{JSONObject answer;
   if(engine.equals("local")){if(!inferencing.compareAndSet(false,true))throw new IllegalStateException("Modelo local ocupado");try{LocalModel.resetCancel();answer=Planner.local(ModelDownload.file(getFilesDir()).getAbsolutePath(),prompt.substring(0,Math.min(prompt.length(),7000)));}finally{inferencing.set(false);}}
   else if(engine.equals("claw"))answer=Planner.openclaw(vault.get("gateway"),prompt,session,work);
   else answer=Planner.openai(vault.get("openai"),Reasoning.MODEL,prompt,prefs.getBoolean("search",true),work);
   work.check();answer.put("seconds",String.format(Locale.US,"%.1f",(System.nanoTime()-started)/1e9));runOnUiThread(()->{if(task!=generation.get()||destroyed)return;plan=answer;selected=-1;savePlan();log(answer.optString("engine")+": plano preparado");finish("Plano pronto. Escolha o próximo passo.");});
  }catch(Exception e){runOnUiThread(()->{if(task!=generation.get()||destroyed)return;log("Falha: "+safeMessage(e));finish(safeMessage(e));});}});
 }
 private boolean command(String q){String s=java.text.Normalizer.normalize(q.toLowerCase(Locale.ROOT),java.text.Normalizer.Form.NFD).replaceAll("\\p{M}","").trim();if(s.equals("parar")){cancel();return true;}if(plan==null)return false;if(s.equals("ler plano")||s.equals("ouvir plano")){speak(plan.optString("summary"));return true;}if(s.equals("salvar plano")){saveNoteFromPlan();return true;}if(s.equals("preparar convite")||s.equals("compartilhar convite")){reviewInvite();return true;}if(s.equals("abrir mapa")){JSONArray opts=plan.optJSONArray("options");if(selected>=0&&opts!=null&&selected<opts.length())openMap(opts.optJSONObject(selected).optString("query"));else toast("Escolha uma opção primeiro.");return true;}return false;}
 private String safeMessage(Exception e){String s=e.getMessage();if(s==null)s=e.getClass().getSimpleName();for(String field:new String[]{"openai","gateway","bridge"}){String secret=vault.get(field);if(!secret.isEmpty())s=s.replace(secret,"[segredo]");}return s.length()>400?s.substring(0,400):s;}
 private void finish(String message){busy=false;phase=message;getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);render();}
 private void cancel(){generation.incrementAndGet();if(job!=null)job.cancel();if(LocalModel.AVAILABLE)LocalModel.cancel();if(tts!=null)tts.stop();busy=false;phase=mode.equals("claw")?"Conexão interrompida. O Gateway pode continuar; ações externas exigem revisão.":"Interrompido. Nenhuma próxima ação será iniciada.";getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);log("Execução interrompida pelo usuário");render();}
 private void savePlan(){if(plan!=null)prefs.edit().putString("plan",plan.toString()).putString("request",lastRequest).putInt("selected",selected).apply();}
 private void saveNoteFromPlan(){if(plan==null)return;try{String id=writeNote(plan.optString("title"),plan.optString("summary")+"\n\n"+invite());log("Plano salvo: "+id);toast("Plano salvo no Registro.");}catch(Exception e){toast(safeMessage(e));}}
 private synchronized String writeNote(String title,String content)throws Exception{if(content.length()>30000)throw new IllegalArgumentException("Nota grande demais");File dir=new File(getFilesDir(),"notes");dir.mkdirs();String id="nota-"+System.currentTimeMillis()+"-"+UUID.randomUUID().toString().substring(0,6)+".txt";try(FileOutputStream out=new FileOutputStream(new File(dir,id))){out.write((title+"\n\n"+content).getBytes("UTF-8"));}return id;}
 private String invite(){if(plan==null)return "";String base=plan.optString("invite");JSONArray opts=plan.optJSONArray("options");if(selected>=0&&opts!=null&&selected<opts.length()){JSONObject o=opts.optJSONObject(selected);base="Pessoal, nossa opção escolhida é "+o.optString("name")+"!\n"+base+"\nLocal: "+o.optString("query")+"\nMapa: https://www.google.com/maps/search/?api=1&query="+Uri.encode(o.optString("query"));}return base;}
 private void reviewInvite(){if(plan==null)return;JSONArray opts=plan.optJSONArray("options");if(opts!=null&&opts.length()>0&&selected<0){toast("Escolha uma opção antes de preparar o convite.");return;}reviewShare(invite());}
 private void reviewShare(String value){EditText editor=new EditText(this);editor.setText(value);editor.setTextSize(16);editor.setMinLines(5);editor.setPadding(dp(20),dp(10),dp(20),dp(10));new AlertDialog.Builder(this).setTitle("Seu convite").setMessage("Revise o texto. Depois, escolha o aplicativo e o destinatário.").setView(editor).setNegativeButton("Voltar",null).setPositiveButton("Compartilhar",(d,w)->{Intent i=new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,editor.getText().toString());try{startActivity(Intent.createChooser(i,"Compartilhar convite"));log("Compartilhamento aberto · envio depende de você");}catch(Exception e){toast("Nenhum aplicativo para compartilhar.");}}).show();}
 private void openMap(String query){if(query==null||query.trim().isEmpty()||query.length()>1000){toast("Endereço inválido.");return;}try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("geo:0,0?q="+Uri.encode(query))));log("Solicitada abertura do mapa: "+query);}catch(ActivityNotFoundException e){openWeb("https://www.google.com/maps/search/?api=1&query="+Uri.encode(query));}}
 private void openWeb(String link){try{Uri u=Uri.parse(link);if(!"https".equals(u.getScheme())||u.getHost()==null)throw new IllegalArgumentException();startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){toast("Não foi possível abrir este link.");}}
 private void voice(){try{Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"pt-BR");i.putExtra(RecognizerIntent.EXTRA_PROMPT,"Qual é a missão?");if(mode.equals("local"))i.putExtra(RecognizerIntent.EXTRA_PREFER_OFFLINE,true);startActivityForResult(i,40);}catch(Exception e){toast("Reconhecimento de voz indisponível. Use o teclado.");}}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==40&&result==RESULT_OK&&data!=null){ArrayList<String> words=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(words!=null&&!words.isEmpty()){page="mission";render();setPrompt(words.get(0));toast("Confira a frase e toque em Planejar.");}}}
 private void speak(String value){if(!ttsReady){toast("Voz do sistema ainda indisponível.");return;}tts.speak(value.substring(0,Math.min(value.length(),3500)),TextToSpeech.QUEUE_FLUSH,null,"maestro");}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 private void log(String s){synchronized(this){try{JSONObject row=new JSONObject().put("time",new SimpleDateFormat("HH:mm:ss",Locale.ROOT).format(new Date())).put("text",s);JSONArray next=new JSONArray().put(row);for(int i=0;i<Math.min(history.length(),59);i++)next.put(history.get(i));history=next;prefs.edit().putString("history",history.toString()).apply();}catch(Exception ignored){}}}
 private EditText field(LinearLayout c,String hint,String value,boolean secret){EditText e=new EditText(this);e.setTextSize(15);e.setTextColor(INK);e.setHintTextColor(MUTED);e.setHint(hint);e.setText(value);e.setSingleLine(true);e.setPadding(dp(12),dp(10),dp(12),dp(10));e.setBackground(bg(BG,10));if(secret)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);add(c,e,10);return e;}
 private boolean modelReady(){return LocalModel.AVAILABLE&&ModelDownload.file(getFilesDir()).length()==ModelDownload.SIZE;}
 private void engines(){
  label(body,"PREPARAÇÃO GUIADA");title(body,"Conectar.\nPreparar. Usar.",30);paragraph(body,"Astra raciocina na nuvem. O executor e as ações ficam neste celular.");
  LinearLayout cloud=card();label(cloud,"1  /  CONECTAR INTELIGÊNCIA");title(cloud,"GPT-6 Astra",24);paragraph(cloud,"Raciocínio alto · pesquisa web · API Responses. A API tem cobrança própria; raciocínio alto pode levar mais tempo. A chave fica criptografada no Maestro.");
  paragraph(cloud,prefs.getBoolean("cloudVerified",false)?"✓ Chave e acesso ao Astra verificados":"Uma conexão inicial verifica o acesso ao modelo na sua conta.");
  EditText key=field(cloud,vault.get("openai").isEmpty()?"Sua chave API OpenAI":"Chave salva · deixe vazio para reutilizar","",true);
  EditText city=field(cloud,"Cidade ou bairro",prefs.getString("city","São Paulo"),false);
  Switch search=new Switch(this);search.setText("Pesquisar na web");search.setTextColor(INK);search.setChecked(prefs.getBoolean("search",true));add(cloud,search,12);
  add(cloud,button(busy?phase:"Conectar e testar Astra",true,()->connectCloud(key.getText().toString().trim(),city.getText().toString().trim(),search.isChecked())),12);
  if(busy)add(cloud,button("Interromper",false,this::cancel),8);
  LinearLayout claw=card();label(claw,"2  /  PREPARAR EXECUTOR LOCAL");title(claw,"OpenClaw no Samsung",22);paragraph(claw,"Na primeira vez: instale o Termux oficial e cole um comando. O instalador prepara Node, OpenClaw, modelo, tokens e ferramentas automaticamente. Pode baixar centenas de MB.");
  paragraph(claw,setupPhase.isEmpty()?"Sem copiar tokens ou preencher configuração do Gateway.":setupPhase);
  add(claw,button("Preparar OpenClaw",true,this::setupClaw),12);
  if(prefs.getBoolean("setupStarted",false)){add(claw,button("Iniciar executor pelo app",false,this::launchExecutor),8);add(claw,button("Verificar conexão",false,this::testGateway),8);}
  paragraph(claw,"Ao parear, a chave também será salva no perfil privado do Termux. O primeiro comando habilita a integração; o Android pede sua permissão antes de o Maestro iniciar comandos fixos no Termux.");
  LinearLayout selector=card();label(selector,"3  /  ESCOLHER MODO");for(String[]m:new String[][]{{"cloud","Astra + ações Android"},{"claw","Astra + OpenClaw local"},{"local","Qwen · offline"}})add(selector,button((mode.equals(m[0])?"✓  ":"")+m[1],mode.equals(m[0]),()->{if(busy){toast("Aguarde a tarefa atual.");return;}mode=m[0];prefs.edit().putString("mode",mode).apply();page="mission";render();}),10);
  LinearLayout local=card();label(local,"OPCIONAL  /  IA OFFLINE");title(local,"Qwen3 · 1,7 bilhão",22);paragraph(local,"Download de 1,11 GB. Pode ficar para depois: o Astra e o OpenClaw funcionam sem este download.");paragraph(local,modelReady()?"✓ Modelo local instalado":LocalModel.AVAILABLE?"Motor ARM64 pronto":"Motor ARM64 indisponível neste aparelho");add(local,text(busy?phase:"Download retomável · SHA-256 verificado",13,GREEN),10);
  add(local,button(modelReady()?"Usar offline":"Baixar modelo local",false,()->{if(modelReady()){mode="local";prefs.edit().putString("mode",mode).apply();page="mission";render();}else download();}),12);
  add(body,button("Apagar chave do Maestro",false,()->new AlertDialog.Builder(this).setTitle("Apagar chave do Maestro?").setMessage("Se já pareou, a cópia no perfil do Termux permanece. Você pode revogar a chave na sua conta OpenAI.").setNegativeButton("Voltar",null).setPositiveButton("Apagar",(d,w)->{try{vault.put("openai","");prefs.edit().putBoolean("cloudVerified",false).apply();render();}catch(Exception e){toast(safeMessage(e));}}).show()),16);
 }
 private void connectCloud(String candidate,String city,boolean search){
  if(busy)return;final String key=candidate.isEmpty()?vault.get("openai"):candidate;if(key.isEmpty()){toast("Informe sua chave OpenAI uma vez.");return;}
  prefs.edit().putString("city",city).putBoolean("search",search).apply();busy=true;phase="Testando acesso ao Astra…";job=new Net.Job();Net.Job work=job;int task=generation.incrementAndGet();render();
  worker.execute(()->{try{JSONObject result=Net.json("https://api.openai.com/v1/responses",key,Reasoning.probe(),work);if(!Reasoning.output(result).trim().equals("MAESTRO_OK"))throw new IOException("O modelo não completou o teste. Tente novamente.");work.check();runOnUiThread(()->{if(destroyed||task!=generation.get())return;try{vault.put("openai",key);prefs.edit().putBoolean("cloudVerified",true).putBoolean("cloudConsent",true).putString("cloudModel",Reasoning.MODEL).apply();log("Acesso ao GPT-6 Astra validado com resposta real");finish("Astra conectado. Agora prepare o executor.");}catch(Exception e){finish(safeMessage(e));}});}catch(Exception e){String error=safeMessage(e).replace(key,"[chave]");runOnUiThread(()->{if(destroyed||task!=generation.get())return;finish("Falha ao conectar: "+error);new AlertDialog.Builder(this).setTitle("Astra não conectado").setMessage(error+"\n\nVerifique acesso ao modelo e saldo da API. O Maestro não troca para um modelo inferior automaticamente.").setPositiveButton("Entendi",null).show();});}});
 }
 private void download(){if(busy){toast("Já existe uma tarefa em andamento.");return;}if(!LocalModel.AVAILABLE){toast("Este aparelho não carregou o motor ARM64.");return;}busy=true;phase="Baixando Qwen3…";job=new Net.Job();Net.Job downloadJob=job;int task=generation.incrementAndGet();getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);render();worker.execute(()->{try{ModelDownload.download(getFilesDir(),downloadJob,(current,total)->{runOnUiThread(()->{if(task!=generation.get()||destroyed)return;phase="Modelo: "+(current*100/total)+"% · "+current/1_000_000+" / "+total/1_000_000+" MB";if(page.equals("engines")){// update text without resetting scroll or input
    updateProgress(body,phase);
   }});});runOnUiThread(()->{if(task!=generation.get()||destroyed)return;log("Qwen3 instalado · SHA-256 verificado");finish("Modelo local pronto.");});}catch(Exception e){runOnUiThread(()->{if(task!=generation.get()||destroyed)return;finish(safeMessage(e));toast(safeMessage(e));});}});}
 private void updateProgress(View view,String value){if(view instanceof TextView){TextView t=(TextView)view;String old=t.getText().toString();if(old.startsWith("Modelo:")||old.startsWith("Baixando Qwen3")||old.startsWith("Download retomável"))t.setText(value);}if(view instanceof android.view.ViewGroup){android.view.ViewGroup g=(android.view.ViewGroup)view;for(int i=0;i<g.getChildCount();i++)updateProgress(g.getChildAt(i),value);}}
 private void testGateway(){
  if(gatewayTesting||destroyed)return;if(prefs.getBoolean("termuxCommandFailed",false)){setupPhase=prefs.getString("setupPhase","");render();return;}String token=vault.get("gateway");if(token.isEmpty()){toast("Toque em Preparar OpenClaw primeiro.");return;}gatewayTesting=true;
  worker.execute(()->{try{JSONObject result=Net.json("http://127.0.0.1:18789/tools/invoke",token,new JSONObject().put("tool","maestro_status").put("args",new JSONObject()),new Net.Job(),12000);JSONObject r=result.optJSONObject("result");JSONObject details=r==null?null:r.optJSONObject("details");if(!result.optBoolean("ok")||details==null||!details.optBoolean("ok")||!details.optString("service").equals("maestro"))throw new IOException("A ponte Maestro não respondeu pelo Gateway.");runOnUiThread(()->{if(destroyed)return;setupPhase="✓ Gateway e ferramentas locais verificados";prefs.edit().putBoolean("gatewayVerified",true).putString("setupPhase",setupPhase).apply();stopService(new Intent(this,SetupService.class));log("OpenClaw executou maestro_status com sucesso");render();toast("OpenClaw conectado. Escolha Astra + OpenClaw local.");});}catch(Exception e){runOnUiThread(()->{if(destroyed)return;setupPhase="Gateway ainda não respondeu. "+safeMessage(e);prefs.edit().putBoolean("gatewayVerified",false).putString("setupPhase",setupPhase).apply();if(page.equals("engines"))render();});}finally{gatewayTesting=false;}});
 }
 private boolean canAutomateTermux(){return TermuxSetup.canAutomate(checkSelfPermission("com.termux.permission.RUN_COMMAND")==android.content.pm.PackageManager.PERMISSION_GRANTED,prefs.getBoolean("termuxBootstrapReady",false));}
 private void setupClaw(){setupClaw(false);}
 private void setupClaw(boolean forceManual){
  if(busy){toast("Aguarde a tarefa atual.");return;}if(!bridgeReady){toast("Reabra o Maestro para iniciar a ponte local.");return;}if(!prefs.getBoolean("cloudVerified",false)||vault.get("openai").isEmpty()){toast("Conecte e teste o Astra primeiro.");return;}
  boolean automatic=!forceManual&&canAutomateTermux();
  AlertDialog.Builder dialog=new AlertDialog.Builder(this).setTitle(automatic?"Reconfigurar OpenClaw":"Primeira preparação no Termux").setMessage(automatic?"O Maestro atualizará os pacotes do Termux e reconfigurará o executor. Pode baixar centenas de MB.":"Toque em Copiar e abrir. No Termux, segure a tela, escolha Colar e pressione Enter.\n\nO comando atualiza os pacotes do Termux, corrige curl/OpenSSL e prepara o OpenClaw. Pode baixar centenas de MB. Mesmo com a permissão Android concedida, esta primeira execução precisa ser colada manualmente.").setNegativeButton("Voltar",null).setPositiveButton(automatic?"Preparar automaticamente":"Copiar e abrir",(d,w)->beginTermuxSetup(automatic));
  if(getPackageManager().getLaunchIntentForPackage("com.termux")==null)dialog.setNeutralButton("Instalar Termux",(d,w)->openWeb("https://github.com/termux/termux-app/releases/latest"));else if(automatic)dialog.setNeutralButton("Colar manualmente",(d,w)->beginTermuxSetup(false));
  dialog.show();
 }
 private void beginTermuxSetup(boolean automatic){
  Intent terminal=getPackageManager().getLaunchIntentForPackage("com.termux");if(terminal==null){toast("Instale e abra o Termux primeiro; depois volte aqui.");return;}
  try{if(vault.get("gateway").isEmpty())vault.put("gateway",UUID.randomUUID().toString()+UUID.randomUUID());String command=TermuxSetup.command(asset("setup/preflight.sh"),pairing.begin());copy(command);setupPhase=automatic?"Atualizando dependências e preparando executor…":"Comando copiado. No Termux: segure a tela → Colar → Enter. Válido por 15 minutos.";prefs.edit().putBoolean("setupStarted",true).putBoolean("termuxCommandFailed",false).putString("setupPhase",setupPhase).apply();startForegroundService(new Intent(this,SetupService.class));render();if(automatic&&canAutomateTermux())sendTermux(new String[]{"-c",command});else startActivity(terminal);}catch(Exception e){toast(safeMessage(e));}
 }
 private void sendTermux(String[] args){
  Intent result=new Intent(this,TermuxResultReceiver.class).setAction("br.com.maestro.TERMUX_RESULT."+UUID.randomUUID());
  PendingIntent callback=PendingIntent.getBroadcast(this,0,result,PendingIntent.FLAG_ONE_SHOT|(Build.VERSION.SDK_INT>=31?PendingIntent.FLAG_MUTABLE:0));
  Intent command=new Intent("com.termux.RUN_COMMAND").setClassName("com.termux","com.termux.app.RunCommandService").putExtra("com.termux.RUN_COMMAND_PATH","/data/data/com.termux/files/usr/bin/bash").putExtra("com.termux.RUN_COMMAND_ARGUMENTS",args).putExtra("com.termux.RUN_COMMAND_WORKDIR","/data/data/com.termux/files/home").putExtra("com.termux.RUN_COMMAND_BACKGROUND",true).putExtra("com.termux.RUN_COMMAND_PENDING_INTENT",callback);
  startService(command);
 }
 private void launchExecutor(){
  if(!prefs.getBoolean("termuxBootstrapReady",false)){setupClaw(true);return;}
  if(checkSelfPermission("com.termux.permission.RUN_COMMAND")!=android.content.pm.PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"com.termux.permission.RUN_COMMAND"},71);return;}
  try{prefs.edit().putBoolean("termuxCommandFailed",false).apply();sendTermux(new String[]{"/data/data/com.termux/files/home/.maestro/start.sh"});setupPhase="Solicitação enviada ao Termux. Aguardando Gateway…";render();new Handler(Looper.getMainLooper()).postDelayed(()->{if(!destroyed){if(prefs.getBoolean("termuxCommandFailed",false)){setupPhase=prefs.getString("setupPhase","");render();}else testGateway();}},10000);}catch(Exception e){toast("Não foi possível iniciar. Use Preparar OpenClaw para reparar a integração.");}
 }
 @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] grants){super.onRequestPermissionsResult(request,permissions,grants);if(request==71&&grants.length>0&&grants[0]==android.content.pm.PackageManager.PERMISSION_GRANTED)launchExecutor();}
 private String asset(String name)throws Exception{return Net.read(getAssets().open(name),150000);}
 private static String shellQuote(String value){return "'"+value.replace("'","'\"'\"'")+"'";}
 private JSONObject installScript()throws Exception{
  JSONObject plugins=new JSONObject();for(String name:new String[]{"index.js","package.json","openclaw.plugin.json"})plugins.put(name,asset("setup/plugin/"+name));
  JSONObject bundle=new JSONObject().put("key",vault.get("openai")).put("bridge",vault.get("bridge")).put("gateway",vault.get("gateway")).put("plugin",plugins).put("configure",asset("setup/configure.cjs"));
  String encoded=android.util.Base64.encodeToString(bundle.toString().getBytes("UTF-8"),android.util.Base64.NO_WRAP);
  String script="MAESTRO_BUNDLE="+shellQuote(encoded)+"\nMAESTRO_BRIDGE="+shellQuote(vault.get("bridge"))+"\nMAESTRO_GATEWAY="+shellQuote(vault.get("gateway"))+"\n"+asset("setup/bootstrap.sh");pairing.consume();return new JSONObject().put("script",script);
 }
 private void copy(String value){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Maestro",value));}
 private void journal(){label(body,"EVIDÊNCIA, NÃO PROMESSA");title(body,"Cada passo\nfica registrado.",30);paragraph(body,"Abrir um aplicativo não confirma um envio, uma reserva ou uma compra.");
  synchronized(pending){if(!pending.isEmpty()){LinearLayout c=card();label(c,"AÇÕES SOLICITADAS PELO OPENCLAW");for(JSONObject a:new ArrayList<>(pending)){String type=a.optString("action"),value=a.optString("value");paragraph(c,(type.equals("map")?"Abrir mapa: ":"Preparar compartilhamento: ")+value);add(c,button("Revisar e continuar",true,()->{synchronized(pending){pending.remove(a);}if(type.equals("map"))openMap(value);else reviewShare(value);log("Solicitação OpenClaw revisada pelo usuário");render();}),8);add(c,button("Recusar",false,()->{synchronized(pending){pending.remove(a);}log("Ação OpenClaw recusada");render();}),6);}}}
  File folder=new File(getFilesDir(),"notes");File[] notes=folder.listFiles();if(notes!=null&&notes.length>0){Arrays.sort(notes,(a,b)->Long.compare(b.lastModified(),a.lastModified()));LinearLayout c=card();label(c,"PLANOS E NOTAS SALVOS");for(int i=0;i<Math.min(notes.length,10);i++){File f=notes[i];add(c,button(f.getName().replace(".txt",""),false,()->{try{String content=Net.read(new FileInputStream(f),100000);new AlertDialog.Builder(this).setTitle("Nota local").setMessage(content).setNegativeButton("Fechar",null).setPositiveButton("Compartilhar",(d,w)->reviewShare(content)).show();}catch(Exception e){toast(safeMessage(e));}}),8);}}
  if(history.length()==0){LinearLayout empty=card();title(empty,"Sua primeira missão começa aqui.",20);paragraph(empty,"Os resultados de ferramentas aparecerão neste registro.");}for(int i=0;i<history.length();i++){JSONObject item=history.optJSONObject(i);if(item==null)continue;LinearLayout c=card();label(c,item.optString("time"));paragraph(c,item.optString("text"));}
 }
 private JSONObject bridgeRequest(String path,JSONObject payload)throws Exception{
  if(path.equals("/setup/install.sh"))return installScript();
  if(path.equals("/setup/status")){String stage=payload.optString("phase","");if(stage.length()>180)throw new IllegalArgumentException("Invalid status");runOnUiThread(()->{if(destroyed)return;setupPhase=stage;SharedPreferences.Editor state=prefs.edit().putString("setupPhase",stage);if(payload.optBoolean("bootstrap_complete"))state.putBoolean("termuxBootstrapReady",true).putBoolean("termuxCommandFailed",false);state.apply();if(page.equals("engines"))render();if(stage.equals("Gateway pronto"))testGateway();});return new JSONObject().put("ok",true);}
  if(path.equals("/health"))return new JSONObject().put("ok",true).put("service","maestro").put("model_ready",modelReady()).put("version","0.2.1");
  if(path.equals("/note")){String title=payload.optString("title","OpenClaw"),text=payload.getString("text");String id=writeNote(title,text);runOnUiThread(()->{if(!destroyed){log("OpenClaw executou: nota salva no aparelho");if(page.equals("journal"))render();}});return new JSONObject().put("status","saved").put("id",id);}
  if(path.equals("/action")){String action=payload.optString("action"),value=payload.optString("value");if(!action.equals("map")&&!action.equals("share"))throw new IllegalArgumentException("Action not allowed");if(value.isEmpty()||value.length()>5000)throw new IllegalArgumentException("Invalid content");String id=UUID.randomUUID().toString();JSONObject item=new JSONObject().put("id",id).put("action",action).put("value",value);synchronized(pending){if(pending.size()>=10)throw new IllegalStateException("Too many pending actions");pending.add(item);}runOnUiThread(()->{if(!destroyed){log("OpenClaw solicitou "+action+" · aguardando revisão no Registro");if(page.equals("journal"))render();}});return new JSONObject().put("id",id).put("status","pending_user_review").put("executed",false);}
  if(path.equals("/v1/models"))return new JSONObject().put("object","list").put("data",new JSONArray().put(new JSONObject().put("id","maestro-qwen").put("object","model").put("owned_by","local")));
  if(path.equals("/v1/chat/completions")){
   if(!modelReady())throw new IllegalStateException("Download local model first");if(payload.optBoolean("stream"))throw new IllegalArgumentException("Streaming not supported");if(payload.has("tools"))throw new IllegalArgumentException("Local model endpoint is text-only; use a reasoning provider for tool calls");if(!inferencing.compareAndSet(false,true))throw new IllegalStateException("Local model busy");
   try{JSONArray messages=payload.getJSONArray("messages");StringBuilder prompt=new StringBuilder();for(int i=0;i<messages.length();i++){JSONObject m=messages.getJSONObject(i);prompt.append(m.optString("role")).append(": ").append(m.optString("content")).append('\n');}if(prompt.length()>7000)throw new IllegalArgumentException("Context too long");LocalModel.resetCancel();String result=LocalModel.generate(ModelDownload.file(getFilesDir()).getAbsolutePath(),prompt.toString(),Math.max(1,Math.min(payload.optInt("max_tokens",420),768)));runOnUiThread(()->{if(!destroyed)log("Modelo local respondeu pela ponte");});return new JSONObject().put("id","local-"+UUID.randomUUID()).put("object","chat.completion").put("created",System.currentTimeMillis()/1000).put("model","maestro-qwen").put("choices",new JSONArray().put(new JSONObject().put("index",0).put("finish_reason","stop").put("message",new JSONObject().put("role","assistant").put("content",result))));}finally{inferencing.set(false);}
  }
  throw new IllegalArgumentException("Unknown endpoint");
 }
 @Override protected void onResume(){super.onResume();if(prefs!=null&&vault!=null){setupPhase=prefs.getString("setupPhase","");if(page.equals("engines"))render();if(prefs.getBoolean("termuxBootstrapReady",false)&&!busy)testGateway();}}
 @Override protected void onDestroy(){destroyed=true;generation.incrementAndGet();if(job!=null)job.cancel();if(LocalModel.AVAILABLE)LocalModel.cancel();if(bridge!=null)bridge.close();stopService(new Intent(this,SetupService.class));worker.shutdownNow();if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
}
